apiVersion: v1
data:
  config.json: <cat ~/.docker/config.json | base64>
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub
  annotations:
   tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/configjson