apiVersion: v1
kind: Secret
metadata:
 name: ssh-key
 annotations:
   tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
data:
  known_hosts: <your ssh known_hosts base64>
  ssh-privatekey: <your ssh privatekey base64>
  config: <your ssh config base64>